// Bundles the Sandhata Design System's token CSS (colour, typography,
// spacing, fonts, base) into a single distributable stylesheet.
//
// The root `tokens/*.css` files (and the `styles.css` manifest that orders
// them) are the single source of truth — this script reads FROM there and
// writes a flat copy to dist/tokens.css. It never edits the root files, so
// there's exactly one place token values are authored; this package is
// just a packaged distribution of them for consumers outside this repo
// (a plain Vite app, Figma Make, etc.) who can't reach ../../tokens.
//
// @import rules (the Google Fonts line in fonts.css) must stay first in
// the output per CSS spec, which the source order already guarantees.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..", "..", "..");
const tokensDir = join(repoRoot, "tokens");
const outDir = join(__dirname, "..", "dist");

// Same order as the root styles.css manifest.
const FILES = ["fonts.css", "colors.css", "typography.css", "spacing.css", "base.css"];

const banner = `/* ============================================================
   @sandhata/spectra-tokens
   Generated from tokens/*.css in the Sandhata Design System repo —
   do not edit this file directly, edit the source and rebuild.
   ============================================================ */\n\n`;

const bundled = banner + FILES.map((f) => readFileSync(join(tokensDir, f), "utf8")).join("\n");

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "tokens.css"), bundled);

console.log(`Wrote dist/tokens.css (${FILES.length} source files, ${bundled.length} bytes)`);
